export const QUERY_KEYS = {
  STUDENT_PROFILE: "student-profile",
  STUDENT_DOCUMENTS: "student-documents",
  STUDENT_SKILLS: "student-skills",
  STUDENT_SOCIAL_LINKS: "student-social-links",
  STUDENT_EXPERIENCES: "student-experiences",
  STUDENT_PROJECTS: "student-projects",
  STUDENT_ADDITIONAL_DETAILS: "student-additional-details",
  STUDENT_ACADEMIC: "student-academic",
  STUDENT_RESUMES: "student-resumes",
  JOBS: "jobs",
  ADMIN_JOBS: "admin-jobs",
  ADMIN_JOB_DETAIL: "admin-job-detail",
  ADMIN_JOB_APPLICANTS: "admin-job-applicants",
} as const;
