export const QUERY_KEYS = {
  STUDENT_PROFILE: "student-profile",
  STUDENT_DOCUMENTS: "student-documents",
  STUDENT_SKILLS: "student-skills",
  STUDENT_SOCIAL_LINKS: "student-social-links",
  STUDENT_EXPERIENCES: "student-experiences",
  STUDENT_PROJECTS: "student-projects",
  STUDENT_ADDITIONAL_DETAILS: "student-additional-details",
  STUDENT_ACADEMIC: "student-academic",
  STUDENT_RESUMES: "student-resumes",
  JOBS: "jobs",
  ADMIN_JOBS: "admin-jobs",
  ADMIN_JOB_DETAIL: "admin-job-detail",
  ADMIN_JOB_APPLICANTS: "admin-job-applicants",
  ADMIN_STUDENTS: "admin-students",
  ADMIN_STUDENT_DETAIL: "admin-student-detail",
  STUDENT_ATS_STATUS: "student-ats-status",
  STUDENT_ATS_HISTORY: "student-ats-history",
  ADMIN_TEAM: "admin-team",
  ADMIN_MESSAGES: "admin-messages",
  ADMIN_DASHBOARD_STATS: "admin-dashboard-stats",
  STUDENT_ANNOUNCEMENTS: "student-announcements",
  ADMIN_EXPORT_PREVIEW: "admin-export-preview",
  ADMIN_EXPORT_STATUS: "admin-export-status",
  ADMIN_ALL_APPLICATIONS: "admin-all-applications",
  EXPORT_LOGS: (page: number) => ['export', 'logs', page] as const,
  OPTIMIZE_RESUME_BY_ID: (id: number) => ['resume', 'optimize', id] as const,
  ALL_RESUMES: ['resume', 'all'] as const,
} as const;

